module.exports = {
  env: {
    browser: true,
    node: true,
    es2021: true,
  },
  parserOptions: {
    ecmaVersion: 2021,
    sourceType: 'module',
  },
  extends: [
    'eslint:recommended',
  ],
  rules: {
    /** Possible Errors */
    'no-dupe-else-if': 'error',
    'no-import-assign': 'error',
    'no-unsafe-optional-chaining': 'error',

    /** Best Practices */
    'array-callback-return': 'error',
    // TODO: seems not supported yet
    // 'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-location': ['error', 'property'],
    eqeqeq: ['error', 'always'],
    'grouped-accessor-pairs': ['error', 'getBeforeSet'],
    'no-caller': 'error',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'warn',
    'no-floating-decimal': 'error',
    'no-implied-eval': 'error',
    'no-iterator': 'error',
    'no-labels': 'error',
    'no-implicit-coercion': 'error',
    'no-lone-blocks': 'error',
    'no-multi-spaces': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-octal-escape': 'error',
    'no-proto': 'error',
    'no-restricted-properties': ['error', { property: '__defineGetter__' }, { property: '__defineSetter__' }],
    'no-return-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': ['error', { allowInParentheses: false }],
    'no-throw-literal': 'error',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-regex-literals': 'error',
    'wrap-iife': ['warn', 'inside', { functionPrototypeMethods: true }],

    /** Variables */
    'no-restricted-globals': [
      'error',
      // builtin
      ...Object.getOwnPropertyNames(Object.prototype),
      // dom
      'blur', 'close', 'closed', 'event', 'external', 'find', 'focus', 'length',
      'name', 'open', 'origin', 'parent', 'scroll', 'status', 'stop', 'top',
    ],
    'no-shadow': ['error', { hoist: 'functions' }],
    'no-undef-init': 'warn',
    // overwrite recommended
    'no-unused-vars': ['error', { args: 'none', ignoreRestSiblings: true }],
    'no-use-before-define': ['error', { functions: false }],

    /** Node.js and CommonJS */
    'no-buffer-constructor': 'error',
    'no-new-require': 'error',
    'no-path-concat': 'error',

    /** Stylistic Issues */
    'array-bracket-newline': ['warn', 'consistent'],
    // 自动删除数组的括号内侧的空格
    'array-bracket-spacing': 'warn',
    'brace-style': 'warn',
    camelcase: ['error', { properties: 'never', ignoreDestructuring: true }],
    'comma-dangle': ['warn', {
      arrays: 'always-multiline',
      objects: 'always-multiline',
      imports: 'always-multiline',
      exports: 'always-multiline',
      functions: 'only-multiline',
    }],
    'comma-spacing': 'warn',
    'comma-style': 'warn',
    'computed-property-spacing': 'warn',
    'eol-last': ['warn', 'always'],
    'func-call-spacing': 'warn',
    'function-call-argument-newline': ['warn', 'consistent'],
    'function-paren-newline': ['warn', 'multiline-arguments'],
    indent: ['warn', 2, { SwitchCase: 1 }],
    'jsx-quotes': ['warn', 'prefer-single'],
    'key-spacing': ['warn', { beforeColon: false, afterColon: true, mode: 'strict' }],
    'keyword-spacing': ['warn', { before: true, after: true }],
    'linebreak-style': 'warn',
    'max-statements-per-line': 'error',
    'new-parens': 'warn',
    'no-array-constructor': 'error',
    'no-bitwise': 'error',
    'no-multi-assign': 'error',
    'no-multiple-empty-lines': ['warn', { max: 2, maxEOF: 0, maxBOF: 0 }],
    'no-new-object': 'error',
    'no-restricted-syntax': [
      'error',
      'ForInStatement',
      {
        selector: '[test.callee.property.name="indexOf"]',
        message: 'The return value of `.indexOf()` was used incorrectly',
      },
    ],
    'no-trailing-spaces': 'warn',
    'no-unneeded-ternary': 'warn',
    'no-whitespace-before-property': 'warn',
    'nonblock-statement-body-position': ['warn', 'beside'],
    'object-curly-newline': ['warn', { consistent: true }],
    'object-curly-spacing': ['warn', 'always'],
    'one-var': ['error', { initialized: 'never' }],
    'operator-assignment': 'warn',
    'operator-linebreak': ['warn', 'before'],
    'quote-props': ['warn', 'as-needed'],
    quotes: ['warn', 'single', { allowTemplateLiterals: true }],
    semi: ['warn', 'never'],
    'semi-spacing': ['warn', { before: false, after: true }],
    'semi-style': ['warn', 'last'],
    'space-before-blocks': 'warn',
    'space-before-function-paren': ['warn', { named: 'never' }],
    'space-in-parens': 'warn',
    'space-infix-ops': 'warn',
    'space-unary-ops': ['warn', { words: true, nonwords: false }],
    'spaced-comment': ['warn', 'always', { markers: ['/'] }],
    'switch-colon-spacing': ['warn', { before: false }],
    'template-tag-spacing': 'warn',
    'unicode-bom': 'warn',

    /** ECMAScript 6 */
    'arrow-spacing': 'warn',
    'no-confusing-arrow': ['error', { allowParens: true }],
    'no-duplicate-imports': 'error',
    'no-useless-computed-key': 'warn',
    'no-useless-constructor': 'warn',
    'no-useless-rename': 'warn',
    'no-var': 'error',
    'object-shorthand': ['warn', 'always'],
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    // overwrite recommended
    'require-yield': 'off',
    'rest-spread-spacing': 'warn',
    'symbol-description': 'error',
    'template-curly-spacing': 'warn',
  },
}
